export enum StepType {
  // SendMessage = "SendMessage",
  // StartFlow = "StartFlow",
  // Actions = "ActiAssignConversationons",
  // Condition = "Condition",
  // SendMail = "SendMail",
  SPLIT_TRAFFIC = "SPLIT_TRAFFIC",
  START_FLOW = "START_FLOW",
  START_FLOW_STEP = "START_FLOW_STEP",
  WAIT = "WAIT",
  LANDING_PAGE = "LANDING_PAGE",

  SEND_TEXT = "SEND_TEXT",
  SEND_IMAGE = "SEND_IMAGE",
  SEND_CARD = "SEND_CARD",
  SEND_CAROUSEL = "SEND_CAROUSEL",
  USER_INPUT = "USER_INPUT",
  SEND_VIDEO = "SEND_VIDEO",
  SEND_GIF = "SEND_GIF",
  SET_DEBOUNCE = "SET_DEBOUNCE", // Debounce each messages
  SEND_MESSENGER_OTN = "SEND_MESSENGER_OTN", // One time notification
  SEND_AUDIO = "SEND_AUDIO",
  SEND_FILE = "SEND_FILE",

  ADD_CONTACT_TAG = "ADD_CONTACT_TAG",
  REMOVE_CONTACT_TAG = "REMOVE_CONTACT_TAG",
  NOTIFY_AGENT = "NOTIFY_AGENT",
  SET_CUSTOM_FIELD = "SET_CUSTOM_FIELD",
  CLEAR_CUSTOM_FIELD = "CLEAR_CUSTOM_FIELD",
  ZAPIER_CUSTOM_LOG = "ZAPIER_CUSTOM_LOG",
  DELETE_CONTACT = "DELETE_CONTACT",
  CALL_API = "CALL_API",

  INBOX_ACTIONS = "INBOX_ACTIONS",
  DISABLE_BOT = "DISABLE_BOT",
  ENABLE_BOT = "ENABLE_BOT",
  ASSIGN_CONVERSATION = "ASSIGN_CONVERSATION",
  AUTO_ASSIGN_CONVERSATION = "AUTO_ASSIGN_CONVERSATION",
  UNASSIGN_CONVERSATION = "UNASSIGN_CONVERSATION",
  ADD_CONTACT_NOTES = "ADD_CONTACT_NOTES",
  FOLLOW_CONVERSATION = "FOLLOW_CONVERSATION",
  UNFOLLOW_CONVERSATION = "UNFOLLOW_CONVERSATION",
  ARCHIVE_CONVERSATION = "ARCHIVE_CONVERSATION",
  UNARCHIVE_CONVERSATION = "UNARCHIVE_CONVERSATION",
  BLOCK_CONTACT = "BLOCK_CONTACT",

  OPENAI_ACTIONS = "OPENAI_ACTIONS",
  OPENAI_GENERATE_TEXT = "OPENAI_GENERATE_TEXT",
  OPENAI_GENERATE_TEXT_AGENT = "OPENAI_GENERATE_TEXT_AGENT",
  OPENAI_GENERATE_TEXT_ADVANCED = "OPENAI_GENERATE_TEXT_ADVANCED",
  OPENAI_GENERATE_TEXT_ASSISTANT = "OPENAI_GENERATE_TEXT_ASSISTANT",
  OPENAI_GENERATE_IMAGE = "OPENAI_GENERATE_IMAGE",
  OPENAI_ANALYZE_IMAGE = "OPENAI_ANALYZE_IMAGE",
  OPENAI_SPEECH_TO_TEXT = "OPENAI_SPEECH_TO_TEXT",
  OPENAI_TEXT_TO_SPEECH = "OPENAI_TEXT_TO_SPEECH",
  OPENAI_DELETE_MESSAGE_HISTORY = "OPENAI_DELETE_MESSAGE_HISTORY",

  EMAIL_ACTIONS = "EMAIL_ACTIONS",
  MARK_EMAIL_VERIFIED = "MARK_EMAIL_VERIFIED",
  OPT_IN_EMAIL = "OPT_IN_EMAIL",
  OPT_OUT_EMAIL = "OPT_OUT_EMAIL",

  ADD_TRIGGER = "ADD_TRIGGER",
  TRIGGER_MAKE = "TRIGGER_MAKE",
  TRIGGER_PABBLY = "TRIGGER_PABBLY",
  TRIGGER_ZAPIER = "TRIGGER_ZAPIER",

  OTHERS = "OTHERS",
  START_ANOTHER_FLOW = "START_ANOTHER_FLOW",
  START_ANOTHER_STEP = "START_ANOTHER_STEP",
  START_EXTERNAL_STEP = "START_EXTERNAL_STEP",
  CANCEL_CONTACT_INPUT = "CANCEL_CONTACT_INPUT",

  TOOLS = "TOOLS",
  GET_DATA_FROM_JSON = "GET_DATA_FROM_JSON",
  FORMAT_DATE = "FORMAT_DATE",
  GENERATE_CODE = "GENERATE_CODE",
  COUNT_CHARACTERS = "COUNT_CHARACTERS",
  PERFORM_ACTION = "PERFORM_ACTION",

  OPEN_WEBSITE = "OPEN_WEBSITE",
  SEND_FLOW_NODE = "SEND_FLOW_NODE",
}

export const disabledCopyActionTypes = [
  StepType.MARK_EMAIL_VERIFIED,
  StepType.OPT_IN_EMAIL,
  StepType.OPT_OUT_EMAIL,
]

export const waitUserReplyActionTypes = [StepType.USER_INPUT]
