packages:
  - apps/*
  - packages/*
  - integrations/*

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@swc/core"
  - msgpackr-extract
  - msw
  - sharp
  - workerd
  - core-js-pure
  - esbuild
  - lefthook
